# Generated by Django 5.0.1 on 2024-06-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.CharField(max_length=200)),
                ('to_date', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=200)),
                ('upload_file', models.FileField(max_length=200, upload_to='')),
            ],
        ),
    ]
