# Generated by Django 5.0.1 on 2024-06-25 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_leave_upload_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='date',
            new_name='idate',
        ),
    ]
