# Generated by Django 5.0.1 on 2024-06-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_dratt'),
    ]

    operations = [
        migrations.CreateModel(
            name='nus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nname', models.CharField(max_length=25)),
                ('npassword', models.CharField(max_length=25)),
                ('nemail', models.CharField(max_length=25)),
            ],
        ),
    ]
