# Generated by Django 5.0.1 on 2024-06-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_nus'),
    ]

    operations = [
        migrations.CreateModel(
            name='nusleave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(max_length=200)),
                ('from_date', models.CharField(max_length=200)),
                ('to_date', models.CharField(max_length=200)),
                ('idate', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=200)),
            ],
        ),
    ]
