# Generated by Django 5.0.6 on 2024-07-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_nuatt'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declained', 'Declained')], default='pending', max_length=20),
        ),
    ]
