# Generated by Django 5.0.6 on 2024-07-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='from_mail',
            field=models.CharField(default='', max_length=200),
        ),
    ]
