# Generated by Django 5.0.6 on 2024-07-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_userre'),
    ]

    operations = [
        migrations.CreateModel(
            name='regcom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarea', models.CharField(max_length=25)),
                ('remail', models.CharField(max_length=25)),
                ('rcomp', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declained', 'Declained')], default='pending', max_length=20)),
            ],
        ),
    ]
